// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/movie.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/movie.go -destination=internal/service/mock/mock_movie_service.go -package mock
//

// Package mock is a generated GoMock package.
package mock

import (
	model "backend/internal/model"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMovieService is a mock of MovieService interface.
type MockMovieService struct {
	ctrl     *gomock.Controller
	recorder *MockMovieServiceMockRecorder
	isgomock struct{}
}

// MockMovieServiceMockRecorder is the mock recorder for MockMovieService.
type MockMovieServiceMockRecorder struct {
	mock *MockMovieService
}

// NewMockMovieService creates a new mock instance.
func NewMockMovieService(ctrl *gomock.Controller) *MockMovieService {
	mock := &MockMovieService{ctrl: ctrl}
	mock.recorder = &MockMovieServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMovieService) EXPECT() *MockMovieServiceMockRecorder {
	return m.recorder
}

// FindAll mocks base method.
func (m *MockMovieService) FindAll(ctx context.Context) ([]*model.ResponseMovie, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx)
	ret0, _ := ret[0].([]*model.ResponseMovie)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockMovieServiceMockRecorder) FindAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockMovieService)(nil).FindAll), ctx)
}

// Save mocks base method.
func (m *MockMovieService) Save(ctx context.Context, movie *model.Movie, genreIds []int64) (*model.ResponseMovie, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, movie, genreIds)
	ret0, _ := ret[0].(*model.ResponseMovie)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockMovieServiceMockRecorder) Save(ctx, movie, genreIds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockMovieService)(nil).Save), ctx, movie, genreIds)
}
