// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/movie.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/movie.go -destination=internal/repository/mock/mock_movie_repository.go -package mock
//

// Package mock is a generated GoMock package.
package mock

import (
	model "backend/internal/model"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMovieRepository is a mock of MovieRepository interface.
type MockMovieRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMovieRepositoryMockRecorder
	isgomock struct{}
}

// MockMovieRepositoryMockRecorder is the mock recorder for MockMovieRepository.
type MockMovieRepositoryMockRecorder struct {
	mock *MockMovieRepository
}

// NewMockMovieRepository creates a new mock instance.
func NewMockMovieRepository(ctrl *gomock.Controller) *MockMovieRepository {
	mock := &MockMovieRepository{ctrl: ctrl}
	mock.recorder = &MockMovieRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMovieRepository) EXPECT() *MockMovieRepositoryMockRecorder {
	return m.recorder
}

// FindAll mocks base method.
func (m *MockMovieRepository) FindAll(ctx context.Context) ([]*model.Movie, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx)
	ret0, _ := ret[0].([]*model.Movie)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockMovieRepositoryMockRecorder) FindAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockMovieRepository)(nil).FindAll), ctx)
}

// GetGenresByMovieId mocks base method.
func (m *MockMovieRepository) GetGenresByMovieId(ctx context.Context, movieId int64) ([]*model.Genre, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGenresByMovieId", ctx, movieId)
	ret0, _ := ret[0].([]*model.Genre)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGenresByMovieId indicates an expected call of GetGenresByMovieId.
func (mr *MockMovieRepositoryMockRecorder) GetGenresByMovieId(ctx, movieId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGenresByMovieId", reflect.TypeOf((*MockMovieRepository)(nil).GetGenresByMovieId), ctx, movieId)
}

// Save mocks base method.
func (m *MockMovieRepository) Save(ctx context.Context, movie *model.Movie, genreIds []int64) (*model.Movie, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, movie, genreIds)
	ret0, _ := ret[0].(*model.Movie)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockMovieRepositoryMockRecorder) Save(ctx, movie, genreIds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockMovieRepository)(nil).Save), ctx, movie, genreIds)
}
