// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/booking.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/booking.go -destination=internal/repository/mock/mock_booking_repository.go -package mock
//

// Package mock is a generated GoMock package.
package mock

import (
	model "backend/internal/model"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockBookingRepository is a mock of BookingRepository interface.
type MockBookingRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBookingRepositoryMockRecorder
	isgomock struct{}
}

// MockBookingRepositoryMockRecorder is the mock recorder for MockBookingRepository.
type MockBookingRepositoryMockRecorder struct {
	mock *MockBookingRepository
}

// NewMockBookingRepository creates a new mock instance.
func NewMockBookingRepository(ctrl *gomock.Controller) *MockBookingRepository {
	mock := &MockBookingRepository{ctrl: ctrl}
	mock.recorder = &MockBookingRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBookingRepository) EXPECT() *MockBookingRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockBookingRepository) Delete(ctx context.Context, bookingId int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, bookingId)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockBookingRepositoryMockRecorder) Delete(ctx, bookingId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockBookingRepository)(nil).Delete), ctx, bookingId)
}

// Save mocks base method.
func (m *MockBookingRepository) Save(ctx context.Context, booking *model.Booking) (*model.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, booking)
	ret0, _ := ret[0].(*model.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockBookingRepositoryMockRecorder) Save(ctx, booking any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockBookingRepository)(nil).Save), ctx, booking)
}

// Update mocks base method.
func (m *MockBookingRepository) Update(ctx context.Context, bookingId int64, booking *model.UpdateBooking) (*model.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, bookingId, booking)
	ret0, _ := ret[0].(*model.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockBookingRepositoryMockRecorder) Update(ctx, bookingId, booking any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockBookingRepository)(nil).Update), ctx, bookingId, booking)
}
